### PR TITLE
Cordova 5+ support

### PR DESCRIPTION
**Pull request by wminkstein**

### CODE REVIEW

**Comment by cainrus** [comment]
Sadly webView.getView is not available for cordova 4.* you need to add some kind of check.

**Comment by guilleferrer** [comment]
I need this in cordova 5+ . Should I checkout the pull request or maybe you could create a new branch for this? Thank you

**Comment by guilleferrer** [comment]
Since I had cordova-plugin-google-analytics 0.8.0 "Google Universal Analytics Plugin"  already installed, installation of the appsFlyer plugin failed: 
* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0

Any idea on how to solve this ?

**Comment by aheadzen** [comment]
This condition should be added as a fix to AppsFlyerPlugin.java:

At top -
`
import android.os.Build;
`

At line 85:
`	
public void onInstallConversionDataLoaded(Map<String, String> conversionData) {
				final String json = new JSONObject(conversionData).toString();
				webView.getView().post(new Runnable() {
					public void run() {
	//					webView.loadUrl("javascript:window.plugins.appsFlyer.onInstallConversionDataLoaded('"+json+"')");
						if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
							webView.sendJavascript("window.plugins.appsFlyer.onInstallConversionDataLoaded('"+json+"')");
						} else {
							webView.loadUrl("javascript:window.plugins.appsFlyer.onInstallConversionDataLoaded('"+json+"')");
						}
					}
				});
			}
`

**Pull request merged**
