### PR TITLE
Fixes compatibility with cordova-ios 6 (#17)

### PR DESCRIPTION
**Pull request by teepark**

### CODE REVIEW

**Comment by af-golan** [comment]
Already done. thanks

**Comment by adityasaxena** [comment]
@af-golan @teepark can you explain to me what this commit is doing and what the problem was ?

**Comment by teepark** [comment]
@adityasaxena I believe it was a compatibility issue with cordova-ios 6. There was no `evaluateJavascript` method.

**Comment by MaximShoustin** [comment]
Take a look on implementation `CDVCommandDelegateImplm` on master branch: [CDVCommandDelegateImpl.m](https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/Public/CDVCommandDelegateImpl.m)
`evalJs ` -> `evalJsHelper/2` -> `[_viewController.webViewEngine evaluateJavaScript:js completionHandler:^(id obj, NSError* error){...}`

As I know using `webViewEngine`  is deprecated so right usage is: 

`[self.commandDelegate evalJs:js];`

**Pull request closed without merging**
