### PR TITLE
fix reportConversionData on IOS

### PR DESCRIPTION
**Pull request by uareurapid**
to fix the #17

### CODE REVIEW

**Comment by jacquesdev** [comment]
Can we please get this merged in?

**Comment by jacquesdev** [comment]
@uareurapid - I am currently testing these changes of yours, but when I try to run up my app, I get the following issue in xcode:

```Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Can't do regex matching on object 1008237086.'

*** First throw call stack:

(0x18683c1c0 0x18527455c 0x187388ab8 0x187266bb4 0x187266288 0x1000c733c 0x1000c7640 0x1000c7284 0x1006bd21c 0x1006c93a8 0x1006d7fa8 0x1006bf304 0x1006ca914 0x1006c0ce4 0x1006cb0f0 0x1006cce6c 0x1006ccbb8 0x1858cd2c8 0x1858ccdb4)

libc++abi.dylib: terminating with uncaught exception of type NSException
```

Any idea why that could be?

**Comment by uareurapid** [comment]
@jacquesdev do you have the entire stack trace? it might help.. strange, it doesn´t seem related with these code changes..

**Comment by jacquesdev** [comment]
@uareurapid - turns out the error was because my appId was an Int not a String, but thanks for your help. I hope this PR gets merged soon :)

**Comment by jacquesdev** [comment]
@af-fess - Can we still get this change merged in? I still had to use this to be able to build ios?

**Pull request closed without merging**
